CC=gcc
CFLAGS=-Wall
LDFLAGS= -lmraa -lm
SOURCES=main.c classifiers.c constants.c training_data_new.c prompt_collect.c

EXECUTABBLES= main.c

all: main

main:
	$(CC) $(CFLAGS) -o main -w $(SOURCES) $(LDFLAGS)
clean:

